name: Build Release
on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        target: # rustc --print target-list
          - x86_64-unknown-linux-musl
          # - aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
          rustup override set stable
          rustup target add --toolchain stable ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Build ${{ matrix.target }}
        timeout-minutes: 60
        run: |
          cross build --release --target ${{ matrix.target }}
          echo "[Info] Build finished"
          mkdir -p release
          echo "[Info] Copy file to release folder"
          cp target/${{ matrix.target }}/release/hellorust release/${{ matrix.target }}-hellorust
          echo "[Info] List release folder"
          ls release

      - name: Github Release 
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release/${{ matrix.target }}-hellorust
          prerelease: ${{ contains(github.ref, '-') }}

 
